version: '3.9'
services:
    nodejs:
      container_name: Node
      build:
         context: .
         dockerfile: Dockerfile
      command: npm start
      volumes:
        - ./www:/usr/src/app
      expose:
        - "3000"
    nginx:
      image: nginx:latest
      container_name: Nginx-NodeJS
      ports:
        - '80:80'
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./www:/usr/share/nginx/html
      depends_on:
        - nodejs
      links:
        - nodejs