version: '3.9'
services:
    nodejs:
      container_name: Node
      build:
         context: .
         dockerfile: Dockerfile
      env_file: .env
      command: npm start
      working_dir: "/app/backend"
      expose:
        - 3000
      ports:
        - "3000:3000"

    nginx:
      image: nginx:latest
      container_name: Nginx-NodeJS
      ports:
        - '80:80'
      volumes:
        - ./etc/nginx/conf.d
      depends_on:
        - nodejs
      links:
        - nodejs